# Default Grafana Flow Panel configuration is in src/clab_io_draw/core/grafana/default_grafana_panel_config.yml

targets:
  # oper + admin state; legend is "oper-state:clab-coxgs-{{host}}:{{ifName}}"
  #
  # ifAdminStatus{instance=~"(spine-coxgs|etc).*"} - 2 == 0
  # or on (instance, ifName)
  # ifOperStatus{ instance=~"(spine-coxgs|etc).*"}
  #
  # now kinda monstrous
  # # if admin down, return 0
  # ifAdminStatus{instance=~"(spine-coxgs|etc).*", ifName!~"([Pp]o|ae).*"} - 2 == 0
  # # else, ifOperStatus == 1 is ok and 2 is bad (operDown), rest (upto 7) are unlikely
  # or on (instance, ifName)
  # (ifOperStatus{instance=~"(spine-coxgs|etc).*", ifName!~"([Pp]o|ae).*"}
  #   # if sum of errored in/out traffic (where defined) > threshold (currently 5 pps), use it as a status
  #   +
  #   (
  #     (
  #       (rate(ifInErrors{instance=~"(spine-coxgs|etc).*", ifName!~"([Pp]o|ae).*"}[$__rate_interval])
  #        or
  #        0 * ifHighSpeed{instance=~"(spine-coxgs|etc).*", ifName!~"([Pp]o|ae).*"})
  #       +
  #       (rate(ifInDiscards{instance=~"(spine-coxgs|etc).*", ifName!~"([Pp]o|ae).*"}[$__rate_interval])
  #        or
  #        0 * ifHighSpeed{instance=~"(spine-coxgs|etc).*", ifName!~"([Pp]o|ae).*"})
  #       +
  #       (rate(ifOutErrors{instance=~"(spine-coxgs|etc).*", ifName!~"([Pp]o|ae).*"}[$__rate_interval])
  #        or
  #        0 * ifHighSpeed{instance=~"(spine-coxgs|etc).*", ifName!~"([Pp]o|ae).*"})
  #       +
  #       (rate(ifOutDiscards{instance=~"(spine-coxgs|etc).*", ifName!~"([Pp]o|ae).*"}[$__rate_interval])
  #        or
  #        0 * ifHighSpeed{instance=~"(spine-coxgs|etc).*", ifName!~"([Pp]o|ae).*"})
  #     ) > 5
  #     or
  #     (0 * ifHighSpeed{instance=~"(spine-coxgs|etc).*", ifName!~"([Pp]o|ae).*"})
  #   )
  # )

  - datasource: prometheus
    expr: "interface_oper_state"
    legend_format: "oper-state:{{source}}:{{interface_name}}"
    instant: false
    range: true
    hide: false

  # traffic in bps: legend is "clab-coxgs-{{host}}:{{ifName}}:out"
  #
  # 8*rate(ifHCOutOctets{instance=~"(spine-coxgs|etc).*"}[$__rate_interval])
  #
  - datasource: prometheus
    expr: "interface_traffic_rate_in_bps"
    legend_format: "{{source}}:{{interface_name}}:in"
    instant: false
    range: true
    hide: false

  # not actively used (yet)
  - datasource: prometheus
    expr: "interface_traffic_rate_out_bps"
    legend_format: "{{source}}:{{interface_name}}:out"
    instant: false
    range: true
    hide: false

  # num of alerts: legend is "num_alerts:{{instance}}"
  # bacic: count by (instance) (ALERTS{alertstate="firing", severity!="info"})
  # more advanced: include icmp unreach and snmp timeout
  #
  # sum by (instance) (
  #   # host is unreachable, at least 2 times during last 1 minute: 200x
  #   (avg_over_time(probe_success{job="blackbox_icmp"}[1m]) < 0.75) + 2000
  #   # snmp timeout: 100x
  #   or on (instance)
  #   (avg_over_time(up[1m]) < 0.75) + 1000
  #   # there are some alerts: < 999
  #   or on (instance)
  #   count by (instance) (ALERTS{alertstate="firing", severity!="info"})
  #   # otherwise, all is fine (has to include it or the pannel will pick last not-null error)
  #   or on (instance)
  #   up{instance=~"(spine-coxgs|etc"}*0)
  #
  - datasource: prometheus
    expr: "device_alerts"
    legend_format: "num_alerts:{{source}}"
    instant: false
    range: true
    hide: false

thresholds:
  operstate:
    # query is designed to return 0 if adminstate is down (see above)
    - {color: "blue",    level:  0}
    # ok
    - {color: "green",   level:  1}
    # oper down but not admin down
    - {color: "red",     level:  2}
    # states from 3 to 7: should not happen: 
    - {color: "purple",  level:  3}
    # green again from last operState until lower "err" threshold
    - {color: "green",   level:  5}
    # bad (error rate too high)
    - {color: "yellow",  level: 10}

  # num of alerts: 0 is fine, upto 999 is geniue alerts, 1000 snmp timeout, 2000 icmp unreach
  # currently drving strokeColor (border), could use e.g. stroke for alerts and label for status
  devstate:
    # 0: ok
    - {color: "white",     level:    0}
    # 0 to 999: num of alerts
    - {color: "yellow",    level:    1}
    # 100x: snmp timeouts (not up)
    - {color: "blue",      level: 1000}
    # 200x: icmp timeouts (unreach)
    - {color: "red",       level: 2000}

  # default, should not be used
  traffic:
    - { color: 'gray',   level:       0 }
    - { color: 'green',  level:  199999 }
    - { color: 'yellow', level:  500000 }
    - { color: 'orange', level: 1000000 }
    - { color: 'red',    level: 5000000 }

  # units are bps (octets*8) to match iface rate
  traffic-1G:
    # grey if inactive
    - {color: "#303030",    level:            0}
    # from 0 to 100Mb/s: shades of green
    - {color: "green",      level:    100000000}
    # from 100 to 500Mb/s: shades from green to yellow
    - {color: "yellow",     level:    500000000}
    # from 500Mb/s to 1Gb/s: shades from yellow to red
    - {color: "dark-red",   level:   1000000000}
  traffic-10G:
    # grey if inactive
    - {color: "#303030",    level:            0}
    # from 0 to 1Gb/s: shades of green
    - {color: "green",      level:   1000000000}
    # from 1 to 5Gb/s: shades from green to yellow
    - {color: "yellow",     level:   5000000000}
    # from 5 to 10Gb/s: shades from yellow to red
    - {color: "dark-red",   level:  10000000000}
  traffic-100G:
    # grey if inactive
    - {color: "#303030",    level:            0}
    # from 0 to 10Gb/s: shades of green
    - {color: "green",      level:  10000000000}
    # from 10 to 50Gb/s: shades from green to yellow
    - {color: "yellow",     level:  50000000000}
    # from 50 to 100Gb/s: shades from yellow to red
    - {color: "dark-red",   level: 100000000000}

# for the links
label_config:
  separator: "replace"
  units: "bps"
  gradientMode: "hue"
  decimalPoints: 1
  # hide until 1Mb/s
  valueMappings:
    - { valueMax:  999999, text: "\u200B" }
    - { valueMin: 1000000 }

# hyperlinks: need `linkRef: detailsLink` in node def
hyperlink_config:
  url: "http://localhost:3000/d/adz264h/router-state-12?var-instance="