# Default Grafana Flow Panel configuration is in src/clab_io_draw/core/grafana/default_grafana_panel_config.yml

targets:
  # oper + admin state; legend is "oper-state:clab-coxgs-{{host}}:{{ifName}}"
  #
  # ifAdminStatus{instance=~"(spine-coxgs|etc).*"} - 2 == 0
  # or on (instance, ifName)
  # ifOperStatus{ instance=~"(spine-coxgs|etc).*"}
  #
  - datasource: prometheus
    expr: "interface_oper_state"
    legend_format: "oper-state:{{source}}:{{interface_name}}"
    instant: false
    range: true
    hide: false

  # traffic in bps: legend is "clab-coxgs-{{host}}:{{ifName}}:out"
  #
  # 8*rate(ifHCOutOctets{instance=~"(spine-coxgs|etc).*"}[$__rate_interval])
  #
  - datasource: prometheus
    expr: "interface_traffic_rate_in_bps"
    legend_format: "{{source}}:{{interface_name}}:in"
    instant: false
    range: true
    hide: false

  # not actively used (yet)
  - datasource: prometheus
    expr: "interface_traffic_rate_out_bps"
    legend_format: "{{source}}:{{interface_name}}:out"
    instant: false
    range: true
    hide: false

  # num of alerts: legend is "num_alerts:{{instance}}"
  #
  # count by (instance) (ALERTS{alertstate="firing", severity!="info"})
  #
  - datasource: prometheus
    expr: "device_alerts"
    legend_format: "num_alerts:{{source}}"
    instant: false
    range: true
    hide: false

thresholds:
  operstate:
    # query is designed to return 0 if adminstate is down (see above)
    - {color: "blue",  level:  0}
    # ok
    - {color: "green",   level:  1}
    # oper down but not admin down
    - {color: "red",     level:  2}
    # should not happen
    - {color: "yellow",    level: 10}

  # num of alerts: even 1 is enough; mb warning=yellow, critical=red (there are no critical alerts here)
  devstate:
    - {color: "yellow",    level:  1}

  # default, should not be used
  traffic:
    - { color: 'gray',   level:       0 }
    - { color: 'green',  level:  199999 }
    - { color: 'yellow', level:  500000 }
    - { color: 'orange', level: 1000000 }
    - { color: 'red',    level: 5000000 }

  # units are bps (octets*8) to match iface rate
  traffic-1G:
    # grey if inactive
    - {color: "#303030",    level:            0}
    # from 0 to 100Mb/s: shades of green
    - {color: "green",      level:    100000000}
    # from 100 to 500Mb/s: shades from green to yellow
    - {color: "yellow",     level:    500000000}
    # from 500Mb/s to 1Gb/s: shades from yellow to red
    - {color: "dark-red",   level:   1000000000}
  traffic-10G:
    # grey if inactive
    - {color: "#303030",    level:            0}
    # from 0 to 1Gb/s: shades of green
    - {color: "green",      level:   1000000000}
    # from 1 to 5Gb/s: shades from green to yellow
    - {color: "yellow",     level:   5000000000}
    # from 5 to 10Gb/s: shades from yellow to red
    - {color: "dark-red",   level:  10000000000}
  traffic-100G:
    # grey if inactive
    - {color: "#303030",    level:            0}
    # from 0 to 10Gb/s: shades of green
    - {color: "green",      level:  10000000000}
    # from 10 to 50Gb/s: shades from green to yellow
    - {color: "yellow",     level:  50000000000}
    # from 50 to 100Gb/s: shades from yellow to red
    - {color: "dark-red",   level: 100000000000}

# for the links
label_config:
  separator: "replace"
  units: "bps"
  gradientMode: "hue"
  decimalPoints: 1
  # hide until 1Mb/s
  valueMappings:
    - { valueMax:  999999, text: "\u200B" }
    - { valueMin: 1000000 }

# hyperlinks: need `linkRef: detailsLink` in node def
hyperlink_config:
  url: "http://localhost:3000/d/adz264h/router-state-12?var-instance=${cell.name}"
  sameTab: false
